FROM alfresco/alfresco-content-repository-community:7.3.0

COPY *.jar /usr/local/tomcat/webapps/alfresco/WEB-INF/lib

COPY alfresco-global.properties /usr/local/tomcat/shared/classes/alfresco-global.properties